/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/airplane/model.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Airplane(props) {
    const { nodes, materials } = useGLTF("./models/airplane/model.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Cylinder.geometry}
                material={nodes.Cylinder.material}
            />
        </group>
    );
}

useGLTF.preload("./models/airplane/model.glb");
