/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/airplane/vintage_airplane.glb 
Author: AGASTRO (https://sketchfab.com/AGASTRO)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-airplane-bf1b7815b339446e80724b9cfffbd25c
Title: Vintage Airplane
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const PROPELLER_SPEED = 25;

export function Vintage_Airplane(props) {
    const { nodes, materials } = useGLTF(
        "./models/airplane/vintage_airplane.glb"
    );
    const properller = useRef();
    const properller2 = useRef();
    useFrame((_state, delta) => {
        properller.current.rotation.y += delta * PROPELLER_SPEED;
        properller2.current.rotation.y += -delta * PROPELLER_SPEED;
    });
    return (
        <group {...props} dispose={null}>
            <group scale={0.01}>
                <group
                    position={[-0.191, 42.319, 35.15]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                >
                    <mesh
                        geometry={
                            nodes[
                                "Vintage_Airplane|silver_engine_cover|Dupli|8_metal_rough_plus001_0"
                            ].geometry
                        }
                        material={materials["metal_rough_plus.001"]}
                    />
                    <mesh
                        geometry={
                            nodes[
                                "Vintage_Airplane|silver_engine_cover|Dupli|8_metal_rough_plus001_0_1"
                            ].geometry
                        }
                        material={materials["metal_rough_plus.001"]}
                    />
                </group>
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|silver_propeler|Dupli|_silver001_0"
                        ].geometry
                    }
                    material={materials["silver.001"]}
                    position={[-0.204, 139.252, 267.652]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|metal_black_front_suspension|Dupli|1_chrome005_0"
                        ].geometry
                    }
                    material={materials["chrome.005"]}
                    position={[0, 52.003, 77.851]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|glass_windows|Dupli|2_glass_clear004_0"
                        ].geometry
                    }
                    material={materials["glass_clear.004"]}
                    position={[-0.001, 164.037, 67.814]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|chrome_brushed_exhoust|Dupli|3_chrome005_0"
                        ].geometry
                    }
                    material={materials["chrome.005"]}
                    position={[-0.697, 105.07, 187.352]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|orange_pipe_top|Dupli|4_chrome005_0"
                        ].geometry
                    }
                    material={materials["chrome.005"]}
                    position={[0, 226.504, 66.792]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|metal_grey_hinges|Dupli|5_plastic_rough001_0"
                        ].geometry
                    }
                    material={materials["plastic_rough.001"]}
                    position={[-7.078, 165.803, -268.465]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|metal_grey_engine_bottom|Dupli|6_plastic_rough001_0"
                        ].geometry
                    }
                    material={materials["plastic_rough.001"]}
                    position={[-22.043, 74.184, 147.293]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|black_cap_holes|Dupli|7_metal_rough002_0"
                        ].geometry
                    }
                    material={materials["metal_rough.002"]}
                    position={[-8.242, 126.106, 58.79]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|metal_grey_engine|Dupli|9_metal_rought_wheels001_0"
                        ].geometry
                    }
                    material={materials["metal_rought_wheels.001"]}
                    position={[-10.58, 119.066, 203.795]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|metal_grey_hasps|Dupli|10_chrome005_0"
                        ].geometry
                    }
                    material={materials["chrome.005"]}
                    position={[0, 90.009, 201.472]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|interior_main|Dupli|11_leather_brun001_0"
                        ].geometry
                    }
                    material={materials["leather_brun.001"]}
                    position={[0, 112.565, 14.428]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|tex_dash_dashboard|Dupli|12_ecran001_0"
                        ].geometry
                    }
                    material={materials["ecran.001"]}
                    position={[0, 136.693, 104.621]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|metal_white_interior|Dupli|13_chrome005_0"
                        ].geometry
                    }
                    material={materials["chrome.005"]}
                    position={[0.177, 175.917, 34.305]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    ref={properller}
                    geometry={
                        nodes[
                            "Vintage_Airplane|tex_prop_propeller|Dupli|14_propeller001_0"
                        ].geometry
                    }
                    material={materials["propeller.001"]}
                    position={[-0.204, 139.252, 264.592]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|tex_body_front_fenders|Dupli|15_carpaint002_0"
                        ].geometry
                    }
                    material={materials["carpaint.002"]}
                    position={[-1.008, 155.158, 46.245]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|red_side_lights|Dupli|16_glass_red004_0"
                        ].geometry
                    }
                    material={materials["glass_red.004"]}
                    position={[0, 192.698, 57.634]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    ref={properller2}
                    geometry={
                        nodes[
                            "Vintage_Airplane|plastic_propeler|Dupli|17_plastic_rough_black002_0"
                        ].geometry
                    }
                    material={materials["plastic_rough_black.002"]}
                    position={[-0.204, 139.252, 266.666]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|metal_grey_exhoust|Dupli|18_metal_rough_plus001_0"
                        ].geometry
                    }
                    material={materials["metal_rough_plus.001"]}
                    position={[35.957, 66.417, 60.724]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes["Vintage_Airplane|tyres_front|Dupli|19_tire002_0"]
                            .geometry
                    }
                    material={materials["tire.002"]}
                    position={[91.786, 19.423, 95.72]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|metal_black_rims|Dupli|20_plastic_rough_black002_0"
                        ].geometry
                    }
                    material={materials["plastic_rough_black.002"]}
                    position={[0, 19.423, 95.72]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|plastic_brake_wires|Dupli|21_plastic_rough_black002_0"
                        ].geometry
                    }
                    material={materials["plastic_rough_black.002"]}
                    position={[7.776, 109.65, 34.795]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|blue_metal_front_suspension|Dupli|22_plastic_rough001_0"
                        ].geometry
                    }
                    material={materials["plastic_rough.001"]}
                    position={[0, 63.687, -9.561]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|chrome_front_suspension001|Dupli|25_chrome005_0"
                        ].geometry
                    }
                    material={materials["chrome.005"]}
                    position={[-0.204, 139.252, 268.434]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|chrome_front_suspension002|Dupli|26_chrome005_0"
                        ].geometry
                    }
                    material={materials["chrome.005"]}
                    position={[-7.271, 118.509, 61.374]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|tyres_front001|Dupli|27_tire002_0"
                        ].geometry
                    }
                    material={materials["tire.002"]}
                    position={[-91.789, 19.423, 95.72]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
                <mesh
                    geometry={
                        nodes[
                            "Vintage_Airplane|tyres_front002|Dupli|28_tire002_0"
                        ].geometry
                    }
                    material={materials["tire.002"]}
                    position={[-0.969, 133.52, -404.915]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={100}
                />
            </group>
        </group>
    );
}

useGLTF.preload("./models/airplane/vintage_airplane.glb");
